# Generated by Django 5.2.4 on 2025-07-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_actor_auditorium_director_producer_movie_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='location',
        ),
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
