# Generated by Django 5.1.6 on 2025-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_theater_auditoriums_alter_actor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='management.seat'),
        ),
    ]
