# Generated by Django 5.1.6 on 2025-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_showtime_available_seats_remove_booking_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stautus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
