# Generated by Django 5.1.6 on 2025-08-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_booking_stautus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='stautus',
            new_name='status',
        ),
    ]
