# Generated by Django 5.1.6 on 2025-08-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_booking_attended_rateservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateservice',
            name='showtime',
        ),
        migrations.AddField(
            model_name='rateservice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_services', to='management.booking'),
        ),
    ]
