# Generated by Django 5.2.4 on 2025-08-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_payment_booking_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='unique_user_message'),
        ),
    ]
