# Generated by Django 5.2.4 on 2025-08-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_notification_unique_user_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_user_message',
        ),
    ]
