# Generated by Django 5.2.4 on 2025-09-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_notification_unique_user_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
