[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://movie-theater-dots.onrender.com/:splat"
  status = 200
  force = true

# For React Router BrowserRouter:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
